"""
PDF Generator — takes the verified, approved resume bullets and
produces a clean, professionally-formatted PDF. Bullets are grouped
by underlying fact type (Skills, Experience, Projects, Education,
Certifications) using the original FactsLedger, rather than shown
as one flat list. Still uses reportlab; still only ever includes
VERIFIED, approved content — never anything rejected by Day 5's
fabrication check.
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from src.schemas.verification import VerificationReport
from src.schemas.facts import FactsLedger, FactType

# Human-readable section titles and the order they should appear in,
# grouped by the underlying Fact type each bullet's source facts belong to.
SECTION_ORDER = [
    (FactType.EXPERIENCE, "Professional Experience"),
    (FactType.PROJECT, "Projects"),
    (FactType.SKILL, "Skills"),
    (FactType.QUANTIFIED_RESULT, "Key Achievements"),
    (FactType.EDUCATION, "Education"),
    (FactType.CERTIFICATION, "Certifications"),
]


def generate_resume_pdf(
    verification_report: VerificationReport,
    ledger: FactsLedger,
    job_title: str,
    output_path: str,
    candidate_name: str = "Candidate Name",
) -> str:
    """Builds a professionally-formatted PDF: header, then approved
    bullets grouped into sections by fact type. Falls back to an
    honest message if no bullets were approved at all.

    NOTE: candidate_name defaults to a placeholder because this
    project's extraction pipeline (Day 2) currently extracts skills/
    experience/education/etc. but not personal contact info (name,
    email, phone) as a distinct fact type. Pass a real name explicitly
    if calling this from the app layer where the user's name is known.
    """

    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()

    name_style = ParagraphStyle(
        "NameStyle", parent=styles["Heading1"], fontSize=20, spaceAfter=2,
        textColor=colors.HexColor("#1a1a1a"),
    )
    subtitle_style = ParagraphStyle(
        "SubtitleStyle", parent=styles["Normal"], fontSize=12, spaceAfter=14,
        textColor=colors.HexColor("#555555"),
    )
    section_header_style = ParagraphStyle(
        "SectionHeader", parent=styles["Heading2"], fontSize=13, spaceBefore=14,
        spaceAfter=6, textColor=colors.HexColor("#2c3e50"),
    )
    bullet_style = ParagraphStyle(
        "BulletStyle", parent=styles["Normal"], fontSize=10.5, leftIndent=14,
        spaceAfter=6, leading=14,
    )
    disclaimer_style = ParagraphStyle(
        "DisclaimerStyle", parent=styles["Normal"], fontSize=7.5,
        textColor=colors.HexColor("#999999"), spaceBefore=20,
    )

    elements = [
        Paragraph(candidate_name, name_style),
        Paragraph(f"Tailored for: {job_title}", subtitle_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")),
        Spacer(1, 10),
    ]

    approved = verification_report.approved_bullets

    if not approved:
        elements.append(Paragraph(
            "No verified bullets were available to include. This may indicate a "
            "weak match between resume and job posting — see the red-flag report "
            "for details on what's missing.",
            bullet_style
        ))
    else:
        # Group approved bullets by the FactType of their first cited fact —
        # a direct, traceable lookup rather than guessing from bullet wording.
        fact_type_lookup = {f.fact_id: f.fact_type for f in ledger.facts}
        sections: dict = {ft: [] for ft, _ in SECTION_ORDER}

        for result in approved:
            primary_type = None
            for fid in result.source_fact_ids:
                if fid in fact_type_lookup:
                    primary_type = fact_type_lookup[fid]
                    break
            if primary_type is None:
                primary_type = FactType.SKILL  # safe, neutral default
            sections[primary_type].append(result.bullet_text)

        for fact_type, section_title in SECTION_ORDER:
            bullets = sections.get(fact_type, [])
            if not bullets:
                continue
            elements.append(Paragraph(section_title, section_header_style))
            for bullet_text in bullets:
                elements.append(Paragraph(f"• {bullet_text}", bullet_style))

    elements.append(Paragraph(
        "Generated by Truth-Checked Resume Tailor — every claim above is "
        "independently verified against the original resume's source facts.",
        disclaimer_style
    ))

    doc.build(elements)
    return output_path